name: playing_cards_lib

description: A library for non ui server side cards logic for standard 52 card decks in your Dart or Flutter app.

version: 0.0.3+1

repository: https://github.com/yehigo/playing_cards_lib

homepage: https://github.com/yehigo/playing_cards_lib


environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
